apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use the official Kubeflow Pipelines manifests as a base
resources:
  - https://github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-multi-user?ref=2.0.5
  - namespace.yaml
  - service-account.yaml
  - ingress.yaml

# Apply our customizations
patchesStrategicMerge:
  - s3-config.yaml

# Patch the default service account to use our IRSA-enabled one
patches:
  - target:
      kind: Deployment
      name: ml-pipeline
    patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: pipeline-runner

# Images to use
images:
  - name: gcr.io/ml-pipeline/api-server
    newTag: '2.0.5'
  - name: gcr.io/ml-pipeline/persistenceagent
    newTag: '2.0.5'
  - name: gcr.io/ml-pipeline/scheduledworkflow
    newTag: '2.0.5'
  - name: gcr.io/ml-pipeline/frontend
    newTag: '2.0.5'
  - name: gcr.io/ml-pipeline/viewer-crd-controller
    newTag: '2.0.5'
  - name: gcr.io/ml-pipeline/visualization-server
    newTag: '2.0.5'
  - name: gcr.io/ml-pipeline/metadata-writer
    newTag: '2.0.5'

namespace: kubeflow
