apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-runner
  namespace: kubeflow
  annotations:
    eks.amazonaws.com/role-arn: ${PIPELINE_RUNNER_ROLE_ARN}
  labels:
    app.kubernetes.io/name: kubeflow-pipelines
    app.kubernetes.io/component: pipeline-runner
